name: Use Android Emulator

description: 'A GitHub Action that sets up an Android emulator.'

runs:
  using: 'docker'
  image: 'docker://my-docker-image'
  steps:
    - name: Checkout
      uses: actions/checkout@v6.0.2
    - name: Enable KVM for Android virtualization
      run: |
        sudo apt-get install qemu-kvm \
        && sudo chown root:kvm /dev/kvm \
        && sudo chmod 666 /dev/kvm
