name: SDK

on:
  workflow_dispatch:
    inputs:
      checkAll:
        description: 'type "check-all" to force checking all packages'
        required: false
        default: ''

                    - name: Setup Go environment
  uses: actions/setup-go@v6.0.0
  with:
    # The Go version to download (if necessary) and use. Supports semver spec and ranges. Be sure to enclose this option in single quotation marks.
    go-version: # optional
    # Path to the go.mod or go.work file.
    go-version-file: # optional
    # Set this option to true if you want the action to always check for the latest available version that satisfies the version spec
    check-latest: # optional
    # Used to pull Go distributions from go-versions. Since there's a default, this is typically not supplied by the user. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
    token: # optional, default is ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # Used to specify whether caching is needed. Set to true, if you'd like to enable caching.
    cache: # optional, default is true
    # Used to specify the path to a dependency file - go.sum
    cache-dependency-path: # optional
    # Target architecture for Go to use. Examples: x86, x64. Will use system architecture by default.
    architecture: # optional
          
  push:
    branches: [main, 'sdk-*']
    paths:
      - .github/workflows/sdk.yml
      - tools/**
      - packages/**
      - yarn.lock
  pull_request:
    paths:
      - .github/workflows/sdk.yml
      - tools/**
      - packages/**
      - yarn.lock
  schedule:
    - cron: 0 14 * * *

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-packages:
    runs-on: ubuntu-24.04
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 100
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            module-scripts:
              - 'packages/expo-module-scripts/**'
              - 'packages/jest-expo/**'
      - name: ⬇️ Fetch commits from base branch
        run: git fetch origin ${{ github.base_ref || github.event.before || 'main' }}:${{ github.base_ref || github.event.before || 'main' }} --depth 100
        if: github.event_name == 'pull_request'
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: ♻️ Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
        with:
          yarn-workspace: 'true'
          yarn-tools: 'true'
      - name: 🧶 Install workspace node modules
        if: steps.expo-caches.outputs.yarn-workspace-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: 🧐 Check packages
        run: |
          echo "Checking packages according to the event name: ${{ github.event_name }}"
          if [[ "${{ github.event_name }}" == "schedule" || "${{ github.event.inputs.checkAll }}" == "check-all" ]] ||
            ${{ steps.filter.outputs.module-scripts }} == "true"; then
            # Check all packages on scheduled events or if requested by workflow_dispatch event.
            bin/expotools check-packages --all
          else
            # On push event check packages changed since previous remote head.
            # In pull requests and workflow_dispatch events check all packages changed in the entire PR.
            bin/expotools check-packages --since ${{ github.base_ref || github.event.before || 'main' }} --core
          fi
      - name: 🔔 Notify on Slack
        uses: 8398a7/action-slack@v3
        if: failure() && (github.event_name == 'schedule' || github.event.ref == 'refs/heads/main' || startsWith(github.event.ref, 'refs/heads/sdk-'))
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_api }}
        with:
          status: ${{ job.status }}
          fields: job,message,ref,eventName,author,took
          author_name: Check packages
